# Generated by Django 3.1 on 2020-08-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Customer', max_length=10),
            preserve_default=False,
        ),
    ]
