# Generated by Django 3.1 on 2020-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(max_length=25)),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
