# Generated by Django 3.1 on 2020-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
