# Generated by Django 3.1 on 2020-08-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storeproduct_transaction_transactionproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='store_id',
            new_name='store',
        ),
    ]
